# Generated by Django 2.1.7 on 2019-03-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0002_auto_20190309_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaikaEnnuste',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaikaEro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaikaTod',
            field=models.CharField(max_length=50),
        ),
    ]
