# Generated by Django 2.1.7 on 2019-03-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0003_auto_20190309_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaikaEnnuste',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaikaTod',
            field=models.DateTimeField(),
        ),
    ]
