# Generated by Django 2.1.7 on 2019-03-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0004_auto_20190313_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juna',
            name='junaLahtoaikaEnnuste',
        ),
        migrations.AddField(
            model_name='juna',
            name='junaLahtoaikaArvio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='juna',
            name='junaMyohassa',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='juna',
            name='junaAjossa',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaikaEro',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaikaTod',
            field=models.DateTimeField(null=True),
        ),
    ]
