# Generated by Django 2.1.7 on 2019-03-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0006_auto_20190325_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juna',
            old_name='tunnus',
            new_name='junaTunnus',
        ),
    ]
