# Generated by Django 2.1.7 on 2019-03-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0007_auto_20190325_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juna',
            old_name='junaLahtoaikaEro',
            new_name='junaMyohassaMin',
        ),
    ]
