# Generated by Django 2.1.7 on 2019-03-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0008_auto_20190325_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='juna',
            name='junaNro',
            field=models.IntegerField(null=True),
        ),
    ]
