# Generated by Django 2.1.7 on 2019-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0009_juna_junanro'),
    ]

    operations = [
        migrations.CreateModel(
            name='JunaSijainti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junaNro', models.IntegerField()),
                ('junaTunnus', models.CharField(max_length=100, null=True)),
                ('junaLahtoaika', models.CharField(max_length=100)),
                ('junaTimeStamp', models.CharField(max_length=100)),
                ('junaKoordLat', models.CharField(max_length=100, null=True)),
                ('junaKoordLong', models.CharField(max_length=100, null=True)),
                ('junaNopeus', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
