# Generated by Django 2.1.7 on 2019-03-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0010_junasijainti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaika',
            field=models.DateTimeField(null=True),
        ),
    ]
