# Generated by Django 2.1.7 on 2019-03-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0011_auto_20190326_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaika',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaikaArvio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juna',
            name='junaLahtoaikaTod',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
