# Generated by Django 2.1.7 on 2019-03-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0012_auto_20190326_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asetukset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SettingName', models.CharField(max_length=100)),
                ('SettingValue', models.CharField(max_length=100, null=True)),
                ('SettingUser', models.CharField(max_length=100, null=True)),
                ('Modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
