# Generated by Django 2.1.7 on 2019-03-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0013_asetukset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asetukset',
            name='Modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
